---
- hosts: dbServers
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles: 
    - role: deploy_couchdb
    - role: couchdb_cluster

- hosts: main-server
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: back_end

- hosts: web-server
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: vue
