---
- hosts: all
  vars_files:
    - host_vars/local_vars.yaml
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: install_environments
    - role: git_clone_sourcefile
    - role: mount-volume

- hosts: dbServers
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles: 
    - role: deploy_couchdb
    - role: couchdb_cluster

