- name: install dependencies
  become: yes
  apt:
    name: ['openmpi-bin','libopenmpi-dev', 'python3-dev']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install backend Python packages
  pip:
    executable: /usr/bin/pip3
    name:
      - mpi4py
      - ijson
      - requests
      - couchdb
      - Mastodon.py
      - flask
      - flask_cors
      - textblob
      - pandas
    state: latest


